Roam-Research/roam-depot

extensions/8bitgentleman/dark-theme-toggle.json
This extension adds a button to the topbar to allow toggling of custom CSS modes. It works by adding and removing the css class `.rm-dark-theme` from the document body.
Custom theme maintainers (or the adventurous) can add support for this in several ways but I recommend using `:root` variables.
```
:root{
//REGULAR THEME COLOR VARIABLES
}
:root .rm-dark-theme {
//DARK MODE COLOR THEME VARIABLES
}
```
=> Dark theme toggle

extensions/8bitgentleman/html-table-import.json
Right-Click menu plugin: Converts an HTML table copied to the clipboard into a Roam Table format. To use select the table text from a webpage ([this table used for testing](https://www.w3schools.com/html/html_tables.asp)) then in roam select the plugin from the right click block menu.
=> html-table-import

extensions/getmatterapp/matter.json
These changes do a couple of things:
For syncing:
1. Decreases the window of time for judging a sync stale, this should reduce the feeling that it's stuck.
2. Added some documentation that indicates it can seem stuck
3. Fixes a bug where stuck syncs wouldn't be restarted under manual sync intervals
For content:
1. De-duplicates the content of article pages by annotation text. This does mean there can be instances where the number of highlights does not match that in Matter (because they would contain the same text). But I figure that doesn't add any new information to the knowledge graph and saves us big headaches for users that uninstall/reinstall the application.
=> improved stale sync, dedups on annotation text

extensions/getmatterapp/matter.json
Escapes quote characters to properly match text within page.
=> Small dedup bugfix - escape quote characters

extensions/phonetonote/phonetonote.json
my repo (https://github.com/phonetonote/ptn-roam-depot) has the extension built, but can also be rebuilt with the `build.sh` script.
the code is mostly the existing phone-to-roam-client (https://github.com/phonetonote/phone-to-roam-client/), but I removed old dependencies, and made an onboarding flow for new and existing users.
=> ptn-roam-depot

extensions/8bitgentleman/clear-sidebar.json
Adds a button to the top of the right sidebar to clear and close all blocks and pages in the sidebar. Not 100% sure about the styling but it looks find in vanilla roam.
=> Clear-sidebar button

extensions/8bitgentleman/tweet-extractor.json
Roam Research Plugin to extract saved tweet text and metadata into your graph. 
To set up the format of your extracted tweet a simple template system is included, found in the Roam Depot plugin settings panel. For each supported `{OPTION}` the variable will be replaced with the extracted tweet information.
Options available to the template are `{TWEET}`, `{URL}`, `{AUTHOR_NAME}`, `{AUTHOR_URL}`, `{DATE}`, `{NEWLINE}`.  A default temlpate is included.
`[[>]] {TWEET} {NEWLINE} [🐦]({URL}) by {AUTHOR_NAME} on [[{DATE}]]`
To trigger the tweet extraction you have two options: Right click plugin or keyboard shortcut
To trigger via a keyboard shortcut click into the block and hit a `CTRL` + `SHIFT` + `E`. (will be remapable once that is exposed via the extension API)
=> Tweet Extract

extensions/8bitgentleman/hide-left-sidebar-buttons.json
Plugin to hide/show the individual buttons in the left sidebar based on a request in the slack channel. Since new plugins have been adding buttons to the sidebar (and more are likely to come) I decided to go the JS route instead of just using CSS `nth-child()`
=> hide-left-sidebar-buttons

extensions/8bitgentleman/hide-left-sidebar-buttons.json
as detailed in #46 setting ids be non-empty strings and can't contain ".", "#", "$", "[", or "]"
=> Left Sidebar Buttons: fix illegal char in settings id

extensions/8bitgentleman/hide-left-sidebar-buttons.json
Y'all were tricky and changed the CSS & HTML structure on me. With Roam's new CSS before this fix the entire left sidebar would disappear. This should fix it
=> FIX Left Sidebar Button CSS Selectors

extensions/phonetonote/phonetonote.json
The main thing this adds is a quick alert to choose if we should make a new ptn key or not:
i used blueprint to keep the dependencies minimal, pretty happy with how it all turned out. this should also fix the small issue where the settings page would open before the ptn key was set, making it less obvious what is going on. i hadn't noticed that because settings load immediately when installing from prod roam depot, not a local extension.
I think I'm now happy with the initial plugin and can get back to building fun new stuff
UPDATE 8/4 - v0.0.4 also fixes the settings, which are currently not always updating correctly.
=> ptn roam-depot v0.0.4

extensions/8bitgentleman/html-table-import.json
This pull changes the name of the HTML Table Import plugin to the more general "Table Import" since it was recently pointed out to me that the plugin works with copied Excel tables as well. Test CSV attached
[test.csv](https://github.com/Roam-Research/roam-depot/files/9285442/test.csv)
=> Name Change: Table Import 

extensions/paulovieira/show-favicon.json
Just remove the stripe account to simplify distributing funds.
More details here: https://github.com/Roam-Research/roam-depot/pull/48
=> remove stripe account from show-favicon extension (see pr #48 for details)

extensions/paulovieira/show-favicon.json
It seems I messed up something before when trying to create the express stripe account. I probably didn't choose the country correctly.
Anyway, I managed to created / finish the stripe account using a bank account in Portugal, with no problems.
More details here: https://github.com/Roam-Research/roam-depot/pull/48#issuecomment-1214469738
=> Update show-favicon with the correct stripe account

extensions/getmatterapp/matter.json
We've recently launched a new feature where a user can add a note at the top level of an article. This is useful for setting the context of the save, general takeaways, etc. This adds note to the article page inside of Roam.
=> Matter: Adds article level note to article page

extensions/8bitgentleman/export-table.json, extensions/8bitgentleman/html-table-import.json
Adds a button to export a table to CSV. 
Right now the button lives in the first cell of the table. 
I'd prefer if it could live next to the hover edit button on the far right but every time I added it to the `hoverparent` with `.hoveronly` clicking on the download button would just edit the block text. 
If there's a way to do this so editing the block isn't triggered on button click please let me know!
=> Export Tables

extensions/phonetonote/phonetonote.json
v0.0.5 overhauls how attached images and documents from telegram work. when phonetonote receives a message with an attached file from telegram, i host it on a cloudflare bucket. when syncing the messages in roam, i now use `window.roamAlphaAPI.util.uploadFile` to store the image/file with the rest of the user's roam files. i can then delete the cloudflare image after syncing, which I do.
v0.0.6 better handles the edge case of unsuccessfully fetching a ptn key as you update your settings
v0.0.7 adds attachmentUrls to smartblocks
=> ptn v0.0.7

extensions/phonetonote/phonetonote.json
Version v0.0.8 removes the default ptn hashtag to resolve https://github.com/phonetonote/ptn-roam-depot/issues/4 and cleans up some other settings wording
=> ptn v0.0.8

extensions/8bitgentleman/clear-sidebar.json
Adds the option to display an alert when clearing the sidebar, as requested on slack. This option is disabled by default.
To do this I converted the extension to use roamjs-components which has the downside of greatly increasing the final size of the compiled extension
=> Clear Sidebar: Alert

extensions/8bitgentleman/code-block-copy.json
Make the inline copy button optional (on as default) as some users don't use that purely for code and found it annoying
=> code block copy: inline copy as optional

extensions/paulovieira/reference-path.json
This is finally ready for review.
There is no stripe acount in the json. This is on purpose as the original work on this plugin was done by @azlen (Azlen Elza). I have contacted him by email about submitting the plugin and he said it was ok. I will contact him later to eventually split any possible payments.
More background here: https://github.com/Roam-Research/roam-depot/pull/48
=> reference path

extensions/8bitgentleman/toggle-uppercase.json
@panterarocks49  looks like the name in the origional JSON was never changed and it has overwritten my "Table Import" extension in the store. My Table Import plugin, which had previously been doing quite well, is now showing as 0 and points to an incorrect extension. This is 100% my bad, apologies, hope the Table Import downloads can be restored 😨
=> FIX Update toggle-uppercase.json

extensions/mlava/focus-mode.json
Allow dynamic update when changing Roam Depot settings - the user can turn on Focus Mode and then change the settings to see their effect.
=> Fixes - Focus Mode

extensions/dvargas92495/workbench.json
Well It's finally here.
I decided to completely rewrite Roam42 and publish it as WorkBench to Roam Depot. All old files are in the `/legacy` file and are not used in the actual submission. They're there to give an idea of what the original code looked like, and to patch any emergencies that come up during the migration. This folder will be removed once WorkBench is live on RoamDepot for a few weeks.
There are probably several questionable instances of logic here - don't be afraid to be critical. I imagine that there are still things I need to clean up before it actually reaches the store.
=> Workbench: Version 2022-09-03-17-44

extensions/mlava/quick-capture.json
Restore delete on import
Create option for labelling in Todoist on import rather than deleting - https://github.com/Roam-Research/roam-depot/pull/200#issuecomment-1249965312 Allow import of Todoist labels and convert to RR tags
=> Bug Fixes for Quick Capture

extensions/digitalmaster/roam-memo.json
Just noticed that the page creation API now throws an error if you try to create a page that already exists: 
It also throws an error if you don't pass it a UID: 
This plugin (and i'm sure many others are broken as a result) 😬
=> Roam Memo: Release v8: Fix Create API Regression

extensions/mlava/todoist-task-management.json
Todoist's API isn't working correctly and they are working on a fix
=> Bug fix - revert Todoist TM to v1 of API for today|overdue calls

extensions/phonetonote/image-generator.json
`image generator` is a new plugin to generate Stable Diffusion images from right inside Roam. It works via the command palette and block context menu. [quick demo here](https://user-images.githubusercontent.com/1139703/191873385-db352955-f334-4cfe-930a-329157d768f4.mp4).
=> New Extension: Image Generator

extensions/rcvd/RoamStudio.json
I can't get Unicode CSS content to work within the plugin (e.g. content: "\e62b";), the backslash will always be removed resulting in a number instead of an icon (see slack question). Temporarily removed it completely until I found a real fix.
=> Bugfix: Completely removed calendar icon in front of date links for the moment

extensions/8bitgentleman/start-page.json
Lets the user set a custom page or block to load automatically on roam start instead of the Daily Notes page
=> New Extension: Startpage

extensions/phonetonote/similar-pages.json
similar pages uses machine learning and graph theory to help you find connections between ideas.
demo and overview - https://www.loom.com/share/d034cbf2909442e5bea4a6bca2a962f9
you can also see more on the [README](https://github.com/phonetonote/similar-pages), including a little about how it works (webworkers and indexeddb only, nothing being sent to a server). happy to answer any questions. I was originally working on this way back before roam depot launched, so excited to finally ship this!
=> New Extension - Similar Pages

extensions/alixlahuec/zotero-roam.json
- fix: fatal crash due to invalid shortcuts ([#96](https://github.com/alixlahuec/zotero-roam/issues/96))
- fix: race condition with Smartblocks ([#97](https://github.com/alixlahuec/zotero-roam/issues/97))
- chore: fix shortcuts validation with empty string ([#100](https://github.com/alixlahuec/zotero-roam/pull/100))
=> zoteroRoam: update to v0.7.7

extensions/alixlahuec/zotero-roam.json
* [fix: ZOTEROITEMCOLLECTIONS doesn't return output](https://github.com/alixlahuec/zotero-roam/pull/110)
* [feat: sort annotations and notes for import](https://github.com/alixlahuec/zotero-roam/pull/102)
* [feat: add custom nesting options for notes](https://github.com/alixlahuec/zotero-roam/pull/112)
* [feat: expand formatting options for autocomplete](https://github.com/alixlahuec/zotero-roam/pull/114)
* [feat: add interface to view logs](https://github.com/alixlahuec/zotero-roam/pull/115)
* [tests: add coverage for SmartBlocks commands](https://github.com/alixlahuec/zotero-roam/pull/111)
* [chore: fix path in README](https://github.com/alixlahuec/zotero-roam/pull/113)
* [chore(deps): update dependency webpack-cli to v5](https://github.com/alixlahuec/zotero-roam/pull/95)
* …
=> Update zoteroRoam - v0.7.8

extensions/hyc/roam-reference-expands.json
If the user check a todo block that has already been referenced, Roam will crash.
=> crucial fix for Reference Expands

README.md
This PR is designed to accomplish the following goals:
- use GitHub's preferred spelling of GitHub (GitHub) instead of the current spelling (Github) to improve Roam's credibility and brand equity and in the medium to long term Roam's market share and profitability I guess
- make @danyalaytekin an official contributor to `roam-depot`
=> Readme: Use GitHub's preferred spelling of GitHub

extensions/phonetonote/image-generator.json
Point to latest version of `image-generator`, which has an updated README describing the correct model version.
This is only a change to the README, no changes to the extension code.
=> Update Image Generator readme

extensions/phonetonote/youtube-transcripts.json
New extension to fetch youtube transcripts and put them into your graph. This uses https://youtubetranscript.com/, which gets them straight from youtube. This does not use whisper or anything fancy (for now).
Demo:
https://user-images.githubusercontent.com/1139703/211221319-cfcf2083-53e7-4163-b071-129923345437.mp4
See the README in the repo for full usage.
=> New Extension: Youtube Transcripts

extensions/8bitgentleman/dark-theme-toggle.json
fix an accidental override of a user's default theme when the CSS blocks were placed at the top of roam/css
=> FIX: Dark Theme Toggle

extensions/mlava/quick-capture.json
replace underscore in Todoist label with space in Roam Research tag
=> Update Quick Capture - rename Todoist labels

extensions/8bitgentleman/self-destructing-blocks.json
Updates from Slack feedback
-  **feat:** add⏱ in front of page links as well as tags
- **feat:** add an option to hide the self-destruct tag
-  **fix:** self-destruction blocks within templates (previously they would be deleted, defeating the whole point of the extension 🤦‍♂️)
- **fix:** update ⏱css when the self-destruct tag is changed by the user
=> Update: Self destructing Blocks

extensions/8bitgentleman/hide-left-sidebar-buttons.json
Two new options as requested on Slack
- Hide Shortcuts header
- Platform dependent toggle (only hide on mobile)
=> Update: Hide Left Sidebar Items

extensions/8bitgentleman/hide-left-sidebar-buttons.json
In the production version of the extensionAPI you can't use settings id paths with some characters. This doesn't present as an issue when testing in a dev environment so I missed it
=> Update: Fix extensionAPI Errors with hide-left-sidebar-buttons

.gitignore, src/community_extensions/comment.clj
This change adds PR shorthand to the Comment Github Action that runs when PR is created / updated. 
Idea is that this can then be used to load a remote developer extension. 
For more detail on remote developer extensions: https://roamresearch.com/#/app/developer-documentation/page/n8ECay0Wl
Highlighted bit in screenshot below is the addition to the markdown content of the comment
Don't know how/ if I can test in production, but given that it works locally, see no reason why it would not work in prod
=> Adds PR Shorthand to the "comment" Github Action

extensions/fbgallet/roam-extension-ref-count.json
@panterarocks49 some users have experienced app freezing with the previous version, on page with a large amout of linked references. This commit should fix the issue.
=> Important fix: Page References Counter

extensions/8bitgentleman/format-blocks-hotkey.json
When blocks are created sometimes metadata is omitted and default styling is assumed. This caused a silent failure of the extension
=> Fix format-blocks-hotkey.json

extensions/dragonforce2010/roam-power-previewer.json
This extension can preview a website content in the sidedrawer, which gives a better roam experience - neat clean notes and easiy preview the website content without going out of roam, to help you focus more in the roam.
This extension's whole idea is to let you stay in roam to focus on your work without going out and meanwhile keep you roam notes clean, without too much blocks nested within which could disturb a lot.
For now, it can only preview the website content, but in the feature, I tend to have more contents in the roam can be previewed in the same way. Reach me out if you have any feature request.
=> new extension:  roam power previewer

extensions/paulovieira/reference-path.json
More details here: https://github.com/paulovieira/roam-reference-path/issues/19
=> improve compatibility between Reference Path and Sticky Headings extensions

extensions/8bitgentleman/todo-progress-bar.json
This is the first extension (I believe) that adds a roam/render component to a user's graph. The idea is to re-load the roam/render codeblock on graph load which preserves a user's existing render references while keeping the ability for me to update the cljs code
=> New Extension: Todo progress bar - Roam/Render component

extensions/getmatterapp/matter.json
Migrates the "sync to daily note" setting to a "sync locations" selector. The user will be able to select between syncing to:
1. Only an article page
2. Only the daily note
3. Both the article page and daily note
=> Matter 1.1.0

extensions/studyduck/roam-save-scrollbar-position.json
Save Scrollbar Position-Saves the scrollbar position of a page when you leave it and restores it when you return
=> New Extension: Save Scrollbar Position

extensions/8bitgentleman/graph-radar-component.json
roam/render component to show the last x edited pages in a graph. Useful for multiplayer graphs and graphs not often visited
=> New Extension: graph-radar component

extensions/8bitgentleman/send-to-graph.json
Use the new backend API to send blocks from one graph to another
https://github.com/Roam-Research/roam-depot/assets/4028391/bc8478be-3166-4b39-8652-48047c5a2c1c
=> New Extension: Send to Graph

extensions/8bitgentleman/tweet-extractor.json
twitter's oembed hasn't been updated to work with x.com yet so the tweet extractor was failing silently with those urls.
=> Fix: Tweet Extractor -> x.com

extensions/hyc/Tabs+.json
@dive2Pro  mistakenly removed the metadata in #761
=> adding back missing metadata to hyc tabs

extensions/8bitgentleman/tag-cycle-component.json
A roam/render component to cycle through a block ref'd list of tags
=> New Extension:Tag-cycle Component.json

extensions/mlava/translate.json
Fix to prompt user for source language instead of using detect via the API. API is now charging for detect calls but not translate calls.
=> Update Translate extension

extensions/qcrao/block-share-card.json
This PR introduces the Block Share Card extension for Roam Research. 
This extension allows users to easily share content blocks from Roam Research as images optimized for mobile and desktop viewing. The functionality enhances the user experience by providing a quick and efficient way to share information in a visually appealing format.
=> add block-share-card extension metafile

extensions/digitalmaster/roam-memo.json
Found a pretty serious bug introduced in this commit last week where no matter what you grade it always results in a "Perfect" grade.
This was introduce [here](https://github.com/digitalmaster/roam-memo/commit/b5693fa095a0c6bf1a7657f33cbc7dc8d2d5fb9c#diff-bb830d0e6ecfec0dcd1c77dd21e86fd88d6aac900a9a491d75f3e5e99892e47dL58-L66) where the existing card data spread follows the selected gradeData.
I've updated the test utils issue that allowed this the slip through and updated test accordingly.
=> Roam Memo: Release v19

extensions/fbgallet/roam-extension-speech-to-roam.json
Note that source repo has change from 'https://github.com/fbgallet/roam-extension-speech-to-roam.git' to 'https://github.com/fbgallet/roam-extension-live-ai-assistant.git'
This is a big update, with a lot of new features and refactoring (see beginning of the readme for main new features)
All functions that directly use the Roam API are in principle gathered here: https://github.com/fbgallet/roam-extension-live-ai-assistant/blob/main/src/utils/roamAPI.js
There are two "sensitive" features:
- the Smart Search Agent uses a fairly complex set of queries via .q API. In my tests it works well, but I do not have a very large graph. Currently, it is not optimized, and I fear it could be slow or even freeze for certain queries in large graphs. I have clearly indicated in the documentation that …
=> Major update Live AI Assistant

extensions/8bitgentleman/send-to-graph.json
Send-to-graph sometimes silently failed while showing success. This happened because we were not awaiting a response from the roam backend
=> FIX: silent failure sending blocks

extensions/hyc/roam-references-radar.json
**Link All Feature**: Click the "Link All Preview" button in the popover to see a preview of all keywords converted to reference links at once. Review the changes and click "Confirm" to apply all links, or "Cancel" to revert.
=> Update: roam-references-radar  

extensions/MannixHu/roam-quick-copy-block-link.json
quick copy block / page desktop link in markdown format
copy such as `[block text or page title](roam://#/app/userxx/page/CovCrrQRU)`
Entrance: 1. right click menu [Extensions - copy desktop link as markdown]  2. shortcut Hotkey
=> New Extension: quick-copy-block-link
