- extensions/dvargas92495/query-builder.json
Reverts Roam-Research/roam-marketplace#4
> Revert "v2022-06-09-02-42 of RoamJS Query Builder"

- extensions/getmatterapp/matter.json
Adds references to highlights created on the daily journal
> Integrates with daily journal

- extensions/oschmid/roam-left-expander.json
See github.com/oschmid/left-expander
> Add Left Expander Extension

- extensions/oschmid/roam-left-expander.json
The demo video in the README isn't showing properly. This should fix it.
> Update Left-Expander extension

- extensions/getmatterapp/matter.json
> Escapes page titles

- extensions/dvargas92495/smartblocks.json
Steps left to do before merging:
- JAVASCRIPT
- JAVASCRIPTASYNC
- J
- JA
- ONBLOCKEXIT
- IF
- IFTRUE
- THEN
- ELSE
> Smartblocks Version: 2022-06-29-23-16

- extensions/phonetonote/phonetonote.json
This fixes a potential race condition if the user adjusts settings directly after installing
> phonetonote: version 2022-07-26

- extensions/phonetonote/phonetonote.json
There were previously issues where the extension was sometimes sending two requests to create a new account or for a sign in token instead of one.
The latest commit attempts to fix that by generally cleaning up the hooks and better managing settings. 
@panterarocks49 if there's any way you could test this like you did the first version, that would be great, as I can't reproduce any of this locally.
> Update phonetonote to v0.0.2

- extensions/mlava/word-count.json
@tonsky 
I decided to nuke my fork and start again.
Here is the first one, and I will be careful to start a new branch for each extension.
Cheers!
> Word Count extension

- extensions/mlava/random-quote.json
@tonsky I believe I've addressed the issues raised at https://github.com/Roam-Research/roam-depot/pull/53#issuecomment-1205554080
Let me know what you think! :-)
> Random quote extension

- extensions/8bitgentleman/tweet-extractor.json
Adds the `AUTHOR_HANDLE` variable option to the template. This is different from a twitter user's `AUTHOR_NAME` which can be changed
> Tweet Extractor - Add AUTHOR_HANDLE

- extensions/mlava/json-webhooks.json
@tonsky 
I hope I've addressed all of the feedback from your previous review. Cheers!
> Json webhooks

- extensions/mlava/send-readwise.json
@tonsky 
I believe I've addressed the feedback you gave me on the prior version.
Cheers!
> Send to Readwise extension

- extensions/mlava/quick-capture.json
@tonsky 
I believe I've addressed the issues raised in the previous PR.
Cheers!
> Add Quick Capture with Todoist extension

- extensions/fbgallet/roam-extension-universal-dropdown.json
Didn't appear in pull request list anymore, I suppose I've made a mistake in pushing last update this night! But it was pushed here 14 days ago.
> Universal Selector

- extensions/mlava/weathercards.json
updated to remove reliance on dayjs library
> Add Weathercards

- extensions/8bitgentleman/code-block-copy.json
Addresses the suggestion and lingering bug from my initial pull #111
> Copy-code-block: Inline Code & bug fix

- extensions/digitalmaster/roam-memo.json
Had 2 weeks off from work and decided to build the plugin I always wished Roam had built in. A simple, easy-to-use, clean, spaced repetition UI. There's still a lot I want to add but I think this is at a ok place to publish and iterate from there.
Looking forward to some feedback 🙏🏽
> Memo - Spaced Repetition for Roam

- extensions/digitalmaster/roam-memo.json
> Memo: V1.0.1

- extensions/readwiseDailyQuote/readwiseDailyQuote.json
- extensions/tedisagolli/roam-readwise-daily-quote.json
Show a quote from your Readwise account in your Daily Note page
> Add Readwise Daily Quote

- extensions/digitalmaster/roam-memo.json
> Memo v1.0.2

- extensions/mlava/todoist-task-management.json
Fixed issue with checking box not completing the task in Todoist
Fixed issue of not being able to have RR tags in task body
> Bug Fixes: fixed create and complete tasks scripts - Todoist TM

- extensions/8bitgentleman/mobile-buttons.json
An extension to add custom buttons to the bottom bar on mobile. First time using a reactComponent in the settings panel, not sure about the styling.
Also if there is a simple way to toggle between formatting (eg bold on/off) I haven't figured it out
> Custom Mobile Buttons

- extensions/mlava/numbered-list.json
as suggested https://github.com/Roam-Research/roam-depot/pull/99#pullrequestreview-1079445829
> update to remove button

- extensions/8bitgentleman/toggle-uppercase.json
Requested on twitter. A simple right click menu plugin to toggle all block text to upper or lower case
> Toggle Text uppercase/lowercase

- extensions/rcvd/RoamStudio.json
- extensions/rcvd/roam-css-system.json
> Roam Studio

- extensions/rcvd/RoamStudio.json
Fixed the class names for unloading the plugin.
> Roam Studio - Fixed Unload

- extensions/mlava/workspaces.json
And allow [[page]] and ((block)) refs in definitions @panterarocks49 as per your suggestion https://github.com/Roam-Research/roam-depot/pull/128#issuecomment-1232272349
> Several bug fixes and improvements - Workspaces

- extensions/8bitgentleman/mobile-buttons.json
Adds a button to delete a block and its children
> Mobile Buttons - New buttons

- extensions/mlava/reading-time.json
Fix no reading time div onload
Updated to allow dynamic update of RT based on changes in Roam Depot settings
> Bug fixes - Reading Time

- extensions/8bitgentleman/tweet-extractor.json
Previously it was possible for a user's template to be overridden by the default template
> FIX: Tweet Extractor Template

- extensions/hyc/roam-hierarchy
- extensions/hyc/roam-toolbar.json
The function bound to document.leave is not called, causing a significant performance drop
> roam-toolbar perf up

- extensions/digitalmaster/roam-memo.json
[Changes v1.0.3](https://github.com/digitalmaster/roam-memo/compare/v1.0.2...v1.0.3)
-
> Update Roam Memo ➞ v1.0.3

- extensions/digitalmaster/roam-memo.json
Sorry forgot to include the [README.md](https://github.com/digitalmaster/roam-depot/blob/main/README.md) update  🙈😅🤓
Thanks for reviewing these so quickly 🙏🏽
> Roam Memo: README.md update

- extensions/Stvad/roam-date.json
via https://github.com/Stvad/roam-date
> Add Roam Date UX plugin

- extensions/rcvd/RoamStudio.json
- Added Masonry Module
- Added Mobile Sidebar Module
- Added various Page Link Settings
- Added various Tags Settings
- Added option to set a different font size on mobile
- Added color for .cmt-labelName in codeblocks
- Fixed small issues within the settings (highlighting a setting, tab bar on mobile, plugin background, search field border)
- Fixed h1 heading font on the right sidebar
- Fixed query padding
- Fixed block hover information
- Fixed toast message color
> Roam Studio: Various enhancements and fixes

- extensions/digitalmaster/roam-memo.json
See changes in [CHANGELOG.md](https://github.com/digitalmaster/roam-memo/commit/1bf198868d88eb640d2aa56292c950659fba5bcc#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
---
Question: Where's the best place to ask questions re: plugin development?
The question i'm curious about is:  Is there something like the `roamAlphaAPI.ui.components.renderBlock()`API but for the breadcrumbs component? If not, any suggestions on how to go about rendering a block's breadcrumbs?
Thanks for your work in reviewing these PRs 🙏🏽
> Roam Memo: Release v6

- extensions/digitalmaster/roam-memo.json
See changelog for updates.
----
Sidenote: Following up on the comment in the last Pr.. assuming it's not too much work on your end, it would be awesome if you could make the breadcrumbs component available through the API. Would save a ton of time on my end. 🤗🤓
Edit: Had some time today so I added a barebones version of it for now.. so no rush at all 🙏🏽
> Roam Memo: Release v7

- extensions/rcvd/RoamStudio.json
This is just a minor bugfix adding one slash to the unicode for the calendar icon - would be awesome if this could be quickly approved. 
Thanks in advance!
> Minor Bugfix - Calendar Icon

- extensions/rcvd/RoamStudio.json
Sorry. Another small updates changing the hover color in roam depot for the craft theme.
> RoamStudio: Another really small bugfix regarding the settings

- extensions/mlava/export-document.json
Reverts Roam-Research/roam-depot#266
> Revert "Bug fixes - Export Documents - fix DOCX export"

- extensions/digitalmaster/roam-memo.json
> Release Roam Memo v9

- extensions/getmatterapp/matter.json
Improved error handling in the case of both access and refresh token expiration.
> Improved error handling in roam-matter

- extensions/rcvd/RoamStudio.json
- Enhancements
- Added options to customize colors, sizes and spacing for headings
- Added an option to add a calendar icon to date links
- Added an option to invert date links (switch light and dark)
- Added an option to hide the sidebar icons and make the main links bold instead
- Added options to customize color, style, background, font size and radius for date links
- Added an option to change the weight for page links and tags
- Added an option to change the font size of tags
- Added an option to customize color, style and weight for reference links
- Added an option to invert tag colors (switch light and dark)
- Added an option to change the font size for code blocks
- Improved visibility for page link color gray in dark mode
- Improved visibility of .rm-Tags
- Added an option to …
> Roam Studio: Added various additional customizations

- extensions/mlava/ultraworking.json
Thanks @panterarocks49 good suggestion!
> Bug fix - Ultraworking - respect Enter key in inputs

- extensions/mlava/poemist.json
> Update Poemist - stanzas to blocks

- extensions/8bitgentleman/start-page.json
as mentions on the slack channel and https://github.com/Roam-Research/roam-depot/pull/348#pullrequestreview-1189059008
> Update: Startpage Fix for Desktop app and Hosted graph

- extensions/fbgallet/roam-extension-find-replace.json
Major update, with a lot of new features...
> Update - Find & Replace

- extensions/8bitgentleman/clear-sidebar.json
Adds the option for a customizable keyboard shortcut as requested on Slack
> Update Clear Sidebar - customizable hotkey

- extensions/hyc/roam-preview-panels.json
- The block in the panel can now be zoom-in and zoom-out
> update: Roam preview panels

- extensions/mlava/send-readwise.json
> Update Readwise - add option to link back to RR blockref from... 

- extensions/hyc/roam-toolbar.json
- click on buttons no longer causes the input to lose focus
> Update roam-toolbar. 

- extensions/mlava/workspaces.json
Switch to allow older style dropdown in RR topbar vs newer modal pop-up select.
> Update Workspaces - layout option in config

- extensions/alixlahuec/zotero-roam.json
* [feat: give visual feedback on import errors](https://github.com/alixlahuec/zotero-roam/pull/124)
* [feat: improve toaster and logs](https://github.com/alixlahuec/zotero-roam/pull/125)
* [feat: improve parsing of Zotero notes](https://github.com/alixlahuec/zotero-roam/pull/127)
* [feat: improve display of Zotero notes in drawer](https://github.com/alixlahuec/zotero-roam/pull/129)
* [feat: improve performance when opening the Search Panel](https://github.com/alixlahuec/zotero-roam/pull/131)
* [infra: extend performance improvements in queries](https://github.com/alixlahuec/zotero-roam/pull/132)
* [feat: enable importing specific notes](https://github.com/alixlahuec/zotero-roam/pull/135)
* [feat: improve sorting and filtering in SemanticScholar …
> Update zoteroRoam - v0.7.10

- extensions/hyc/roam-aliases.json
highlight unlink words:
perf up: 
before:
after:
> Update:  Aliases

- extensions/mlava/toc.json
Compatible with Augmented Headings
Fix attributes and other non-headings showing in TOC
> Update TOC - multiple fixes

- extensions/mlava/augmented-headings.json
> Update Aug Headings - clarify readme and description

- extensions/mlava/hide-topbar-buttons.json
to account for left sidebar open/close refreshing the topbar
> Bug fix - Hide Topbar Buttons - add mutation observer

- extensions/LayBacc/roam-ai.json
https://twitter.com/Lay_Bacc/status/1621895598747127808
> added "🧱 Load Context" mode to Roam AI

- src/community_extensions/core.clj
- src/community_extensions/publish.clj
https://roamresearch.com/#/app/roamteam/page/1tgyAJCDH
> Record extension created/updated timestamps

- extensions/alixlahuec/zotero-roam.json
* [fix: tags with hyphen and special characters aren't processed correctly](https://github.com/alixlahuec/zotero-roam/pull/153)
* [fix: styling of multiselect input in Explorer](https://github.com/alixlahuec/zotero-roam/pull/173)
* [fix: excessive API calls due to broken `since` param](https://github.com/alixlahuec/zotero-roam/pull/176)
* [infra: fix assets path in release-it config](https://github.com/alixlahuec/zotero-roam/pull/149)
* [infra(fix): only publish releases related to target branch](https://github.com/alixlahuec/zotero-roam/pull/151)
* [chore(deps): update dependency css-loader to ^6.7.3](https://github.com/alixlahuec/zotero-roam/pull/150)
* [chore(deps): update dependency @babel/core to ^7.20.7](https://github.com/alixlahuec/zotero-roam/pull/154)
* [chore(deps): update …
> Update zoteroRoam - v0.7.11

- extensions/8bitgentleman/clear-sidebar.json
Adds native hotkey support and an options to toggle the open/closed status of all sidebar blocks
> Update: Clear right sidebar

- extensions/digitalmaster/roam-memo.json
> Roam Memo: Release v13

- extensions/mlava/yesterday-tomorrow.json
Also handle yesterday/tomorrow button click on /search page
> Update Yesterday Tomorrow - handle edge case of DNP with unusual uid

- extensions/8bitgentleman/format-blocks-hotkey.json
Adds hotkeys for various block formatting options
> New extension: format blocks hotkey

- extensions/hyc/roam-hierarchy.json
> fix: Hierarchy

- extensions/8bitgentleman/tweet-extractor.json
Falls back on the old oembed scraping if the API is unstable
> FIX:Tweet-extractor failure due to Twitter API error

- extensions/8bitgentleman/mobile-buttons.json
> Update Custom Mobile Buttons

- extensions/phonetonote/phonetonote.json
Smartblocks with images and no caption were previously breaking, this should fix that.
> phonetonote update: better smartblock images

- extensions/dvargas92495/developer.json
- extensions/dvargas92495/dropbox.json
- extensions/dvargas92495/giphy.json
- extensions/dvargas92495/google.json
- extensions/dvargas92495/hypothesis.json
- extensions/dvargas92495/mapbox.json
- extensions/dvargas92495/otter.json
- extensions/dvargas92495/oura-ring.json
- extensions/dvargas92495/presentation.json
- extensions/dvargas92495/query-builder.json
- extensions/dvargas92495/slack.json
- extensions/dvargas92495/smartblocks.json
- extensions/dvargas92495/todo-trigger.json
- extensions/dvargas92495/twitter.json
- extensions/dvargas92495/workbench.json
Just switching the Stripe account ids from one business entity (my personal LLC) to another (SamePage's private corp) for simplifying tax/accounting purposes
> Switching Stripe account id for dvargas92495 extensions

- extensions/dragonforce2010/roam-power-themes.json
> new extension: roam power themes - refactored pr of #593

- extensions/mlava/export-document.json
Large update - removed all nodejs scripts and now POST to server on Heroku.
Increase number of conversion formats.
> Update Export Documents - now using Pandoc

- extensions/hyc/switch+.json
enhance:: remember query text in every stack
> Update: switch+

- extensions/mlava/auto-DNP.json
Addresses:
https://github.com/Roam-Research/roam-depot/pull/630#issuecomment-1586558326
@baibhavbista
> Update auto-DNP - add command to manually paste template

- extensions/hyc/roam-page-history.json
1. Save the URL of the history file in localStorage in case someone uninstalls the plugin by accident
2. Fix the lag when rendering code blocks.
3. Feat Delete record
> Update Page History

- extensions/hyc/roam-preview-panels.json
fix: https://github.com/dive2Pro/roam-preview-panels/issues/5 
fix: rendered content position
fix: https://github.com/dive2Pro/roam-preview-panels/issues/4
> Update roam preview panels

- extensions/hyc/roam-aliases.json
fix: remount unlink aliases div twice
fix: mount unlink aliases wrong place
> Update roam aliases

- extensions/hyc/roam-search+.json
fix https://app.slack.com/client/TNEAEL9QW/CN2L1UUHY/thread/CN2L1UUHY-1690566492.292169
> Fix roam-search+ 

- extensions/dismory/marco-polo.json
Add new extension: Marco Polo - CJK Symbols Converter for Roam Research.
> Create new extension: Marco Polo

- extensions/hyc/Tabs+.json
fix: https://github.com/dive2Pro/roam-tabs/issues/2
feat: https://github.com/dive2Pro/roam-tabs/issues/3
> update Roam Tabs

- extensions/mlava/workspaces.json
https://roamresearch.slack.com/archives/D044AC9ALJ3/p1695023133908799
@baibhavbista
> Update Workspaces - fix autosave interval bug

- extensions/alixlahuec/zotero-roam.json
* incorrect items are shown in DNP menus ([`#396`](https://github.com/alixlahuec/zotero-roam/pull/396))
* Switch to Typescript completed
* Switch to SASS
* Dependency updates
> zoteroRoam - v0.7.20

- extensions/alixlahuec/zotero-roam.json
* [fix: icon context menu doesn't display correctly](https://github.com/alixlahuec/zotero-roam/pull/420)
* [chore(deps): update jest to ^29.7.0](https://github.com/alixlahuec/zotero-roam/pull/405)
* [chore(deps): update dependency jest-runner-eslint](https://github.com/alixlahuec/zotero-roam/pull/408)
* [fix(deps): update tanstack-query monorepo](https://github.com/alixlahuec/zotero-roam/pull/402)
* [chore(deps): update babel monorepo to ^7.22.20](https://github.com/alixlahuec/zotero-roam/pull/399)
* [chore(deps): update dependency chromatic to ^7.2.0](https://github.com/alixlahuec/zotero-roam/pull/409)
* [chore(deps): update storybook core to ^7.4.4](https://github.com/alixlahuec/zotero-roam/pull/401)
* [fix(deps): update dependency axios-retry to …
> zoteroRoam - v0.7.21

- extensions/mlava/numbered-list.json
- added remove numbering function
> Update Numbered List

- extensions/mlava/sidebar-separators.json
add five more possible separators
> Update Sidebar Separators

- extensions/mehboob elahi /roam _preview_window.json
add new commit id.
Made the requested change of clearing interval when unload in the extension.js
> Create roam _preview_window.json

- extensions/mlava/workspaces.json
@baibhavbista - this is intended to fix the number of writes on autosave
> Update Workspaces - reduce writes for autosave

- extensions/LayBacc/roam-ai.json
sorry about the long delay m(_ _)m
- supporting the latest models: GPT-4, DALL-E 3 etc. 
- cleaned up modes and simplified UX for "load context" 
https://www.loom.com/share/046f983192cb4cbb954ba3b8541f3645
> Roam AI Feb 2024 update: fixed model usage, consolidated UX

- extensions/tombarys/nautilus.json
bugfix : now not replacing render string template with defaults after onload
> Nautilus: Support for 12h time format, for custom start time and bugfixes

- extensions/mlava/word-count.json
fixes: https://github.com/mlava/word-count/issues/1
> Update Word Count - add support for Chinese, Japanese and Korean ideographs

- extensions/dragonforce2010/roam-power-themes.json
do not merge for now, still in process
> Feat/roam power themes - implement config center 3.0

- extensions/mlava/todo-teleport.json
fixes: https://github.com/mlava/todo-teleport/issues/2
> Update Todo Teleport - option to leave behind a blockref, teleport date tags

- extensions/mlava/oblique-strategies.json
fix for css collisions with other izitoast extensions
> Update Oblique Strategies

- extensions/digitalmaster/roam-memo.json
See change log [here](https://github.com/digitalmaster/roam-memo/blob/main/CHANGELOG.md).
> Roam Memo: Release v16

- extensions/tombarys/nautilus.json
First PR is just for testing purposes.
- checking for `running` in extension
- checking for component code update
- removed handling the `nautilus-disabled`
> Nautilus: Changing the way how it installs itself 

- extensions/mlava/random-quote.json
remove two dead API sources
- Ted Lasso
- Futurama
> Update Random Quotes

- extensions/mlava/wikipedia.json
fix for error on featured content
> Bug Fix - Wikipedia

- extensions/fbgallet/roam-extension-full-calendar.json
@panterarocks49 in the mean time, i've added the possibility to add tags directly from the multiselect input !
> Update: Full calendar

- extensions/mlava/word-count.json
> Update Word Count

- extensions/mlava/currency-converter.json
Add right-click menu Extensions option (blockContextMenu)
> Update Currency Converter

- extensions/mlava/todoist-task-management.json
> Bug Fix - Todoist TM

- extensions/mlava/crosswords.json
Better handling for when a crossword has special features like shaded squares - show a message to user to explain failure
> Bug Fix - Crosswords

- extensions/8bitgentleman/self-destructing-blocks.json
Updates the README for clarity
> Update self-destructing-blocks README

- extensions/8bitgentleman/roam-crm.json
This is a pretty big extension that harnesses your graph as a relationship management tool.  Actually it's the biggest extension I've done so far 🎉. Take a look at the README first as there are many many features.
- 'People' pages have specific attribute metadata 
- A quick Agenda Addr
- Contact Reminders
- Birthday Reminders
- Google calendar event sync
- Full Page CRM UI
- And more
To help with testing here is a test graph with ~100 people which I have been using. 
[person-crm-testing.zip](https://github.com/user-attachments/files/16103560/person-crm-testing.zip)
Drop me a message or DM if you have questions
> Roam CRM / Relationship Management Tool

- extensions/mlava/shortcode-embeds.json
manage Instagram and TikTok links
> Update Shortcode Embeds

- extensions/dvargas92495/workbench.json
Reverts Roam-Research/roam-depot#923
> Revert "Workbench: Version 1.6.0"

- extensions/8bitgentleman/tag-painter.json
Quickly and easily customize the appearance of your tags within Roam
> New extension: tag-painter.json

- extensions/8bitgentleman/block-distributor.json
https://github.com/user-attachments/assets/27c156cc-3e4c-4aab-89ca-452bd3da78ba
> New extension: block-distributor.json

- extensions/abhayprasanna/random-block.json
changes: https://github.com/abhayprasanna/roam-random-block/pull/3
> Update "Random Block" extension

- extensions/mlava/random-quote.json
- extensions/mlava/todoist-task-management.json
fix for checked tasks not syncing to Todoist
> Bug fix - Todoist task management

- extensions/mlava/random-quote.json
> Bug fix - Random Quotes

- extensions/dragonforce2010/roam-website-title-parser.json
Add markdown link detection to avoid re-processing Improve URL replacement logic with negative lookbehind/lookahead Add content validation before processing URLs
Enhance error handling and task tracking
Fix issue with duplicate URL processing in same block
> feat: optimize URL parsing and prevent duplicate processing

- extensions/8bitgentleman/bluesky-extractor.json
Extract Bluesky posts into your Roam Research graph with formatted text and images.
> New Extension: Bluesky Extractor

- extensions/8bitgentleman/bluesky-post.json
Create Bluesky posts and threads from your Roam Research graph
> New Extension: Post to Bluesky

- extensions/8bitgentleman/todo-progress-bar.json
This is a small update to fix the docs
> Update todo-progress-bar - Small fix

- extensions/mlava/focus-mode.json
fixed compatibility issue for fullscreen using Roam Studio
> Update Focus Mode

- extensions/mlava/random-quote.json
fix for insecure quotable.io address
> Update Random Quote

- extensions/sweenzor/autopin.json
Changed the text of the readme for clarity
> Update Autopin readme

- extensions/DiscourseGraphs/discourse-graph.json
Let me know if there are any issues 👍.
Tagging @sid597 for visibility.
> New Extension: Discourse Graph

- extensions/hyc/roam-recents.json
this plugin will provide users with a view to review the pages they have recently visited.
> New Plugin: Roam Recents

- extensions/fbgallet/roam-extension-speech-to-roam.json
Strangely, Toaster module was not imported in another module and it was not a pb in dev, but it prevents the extension to load in production!
It was just a line of code, it's fixed
> Live ai assistant - small but critical fix (currently the extension isn't loaded)

- extensions/fbgallet/roam-extension-speech-to-roam.json
Hopefully this one is the good one !
> Live ai assistant - fix

- extensions/fbgallet/roam-extension-speech-to-roam.json
There was still a few bugs crashing the context menu for new users or when using context !
I've also fixed an issue with style definition and inline context, and added a help dialog.
> Live ai assistant - small (but important) fixes

- extensions/hyc/roam-recents.json
compatible with blueprint theme.
> Update: Roam Recents 

- extensions/mlava/wotd.json
previously used APIs now all defunct
migrate to wordnik api
> Update Word of the Day

- extensions/mlava/perplexity.json
use block/props for message history storage instead of coding into the SB button
@panterarocks49 thanks for the tip
> Update Perplexity AI

- extensions/8bitgentleman/todo-progress-bar.json
small update to the css transition and adding an option to show/hide percentage
> QOL todo-progress-bar.json updated

- extensions/qcrao/learn-english-in-RR.json
- Add Incremental Extraction.
- Add send to Anki function.
> update: Learn English in RR

- extensions/qcrao/nicer-code-block-copy.json
🔧 Changes Based on the Original Project ([roam-depot-copy-code-block](https://github.com/8bitgentleman/roam-depot-copy-code-block/tree/main))
- Added support for copying highlighted text
- Copy buttons for inline code and highlights only appear on hover (less visual clutter)
- Shows visual feedback (✓ icon) when content is successfully copied
- Fixed the issue where code blocks could not be copied
- Added debounced DOM mutation observer for better performance and reliability
- Improved icon design and overall UI polish
- Introduced separate toggle settings for inline code and highlighted text copy buttons
> New Extension: Nicer Code Block Copy

- extensions/mlava/yesterday-tomorrow.json
Add option for user-configurable buttons to skip back or forward a number of days
> Update Yesterday Tomorrow

- extensions/mlava/todo-teleport.json
(hopefully) a fix for https://github.com/mlava/todo-teleport/issues/1
@Christian-Klaperek
> Update Todo Teleport
